### ISSUE TITLE
verwijder onnodige files

### ISSUE THREAD

**Issue by bwitzen** [JrSchild/Ghost#5]
- Denk hierbij vooral aan Xcode-specifieke files, maar zorg ervoor dat alle files die niet nodig zijn voor de App zelf weggehaald zijn.

**Comment by JrSchild** [comment]
Hi Ben,
Kan je wat specifieker zijn? Volgens mij heb ik zulke files nooit gecommit.

**Comment by bwitzen** [comment]
lijkt op een vergissing, kan ze ook niet vinden
